import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrivateElement from "./components/PrivateElement";
import Navbar from "./components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Financy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <PrivateElement>
          <Navbar />
        </PrivateElement>
        <main className="flex justify-center">
          <div className="w-7xl px-8 mt-12">{children}</div>
        </main>
      </body>
    </html>
  );
}
