import { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import PrivateElement from "./components/PrivateElement";
import { Toaster } from "react-hot-toast";
import Header from "./components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Financy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100`}>
        <Toaster position="bottom-right" reverseOrder={false} />
        <PrivateElement>
          <Header />
        </PrivateElement>
        <main className="flex justify-center">
          <div className="w-7xl px-8">{children}</div>
        </main>
      </body>
    </html>
  );
}
